### ISSUE TITLE
gumbo-parser is archived 

### ISSUE THREAD

**Issue by xland** [litehtml/litehtml#277]
`gumbo-parser` is archived 
And this project has been unmaintained since 2016.
Will `litehtml` depend on this project in the future?

**Comment by tordex** [comment]
Do you know any other project to parse HTML?

**Comment by stasoid** [comment]
Obvious candidate to replace gumbo is HTML parser from lexbor project https://github.com/lexbor/lexbor (former https://github.com/lexborisov/myhtml),
it has some goodies that gumbo doesn't have, like support for encodings and parsing by chunks, it is also probably faster.

However I must say that it will be a long time, if ever, when gumbo will become outdated. The reason for this is that HTML parser is considered
"complete", it is unlikely to be changed in any significant way. This is just my feeling, I can't support it by quoting people editing the standard.
Also, I got involved in some parser shenanigans recently https://github.com/whatwg/html/issues/9559 and I was surprised to see that the parser code 
in Chrome, and probably in Firefox too is quite outdated. Probably even gumbo has fresher code than major browsers. 
So, again, it's not a big deal because HTML parser standard changes very little with time.

So I think if we ever switch to lexbor parser we should do it more because it is just overall better parser than gumbo 
(it looks like it), and less because gumbo is outdated.

**Comment by tordex** [comment]
Thank you. I'll take a look at these projects.
In the future I plan to make adapter for html (and maybe for css) parser (see issue #49 ). So it will possible to use any parser.

**Comment by txgk** [comment]
Hi, gumbo-parser maintainer here! I'd like to point out that gumbo-parser isn't dead - its ideas are continued in https://codeberg.org/grisha/gumbo-parser repository, which many package repositories switched to in these latter months (https://repology.org/project/gumbo-parser/versions). The idea behind this is to just continue maintainership of original gumbo-parser by fixing bugs and keeping it compilable with modern tools. I did this because one of my projects depend on gumbo-parser basically.
