### ISSUE TITLE
namespace vs. no namespace & proper std includes

### ISSUE THREAD

**Issue by asmaloney** [litehtml/litehtml#346]
I've noticed that sometimes `std::` is included, sometimes it isn't (especially with `string` & `shared_ptr`):

```cpp
bool parse(const string& text);
...
using ptr    = shared_ptr<css_selector>;
using vector = std::vector<css_selector::ptr>;
```

and sometimes the headers for them aren't included (`<string>` and `<vector>`, etc.). Obviously when compiling they are defined because of the order they are included, but some IDEs (like mine) display a bunch of errors about undeclared identifiers in the editor because they are missing in certain places.

Would you accept PRs to add `std::` where it should be and `#include`s where they should be? (There's also some include cleanup that can happen - some are included unnecessarily.)

Though maybe I should wait on `std::` for a clang-format file because it could involve a bunch of reformatting...

**Comment by tordex** [comment]
As for me, I prefer using ```std::```. As I see, @stasoid prefer not using namespace. I don't see big issue with this. But let's discuss this :)

**Comment by asmaloney** [comment]
A least we all agree that `using namespace std;` is evil, right? 😆 

Here's where I'm coming from - this is what most of the headers look like for me (this is just the one I happened to have open):

<img width="1111" alt="Screen Shot 2024-04-26 at 16 05 53 PM" src="https://github.com/litehtml/litehtml/assets/391371/927db404-d6ba-424f-a424-1399fde4e5ab">

All of these are caused by the two things I brought up.

So for me it would be a lot easier to read and work with if... well, if I didn't have all those errors showing 😄

**Comment by stasoid** [comment]
Yes, `std::` and `litehtml::` annoy me a lot. Main reason why their use is inconsistent is because I remove them when I see them, I didn't do search/replace on the whole code. Also, in things like `using vector = std::vector<css_selector::ptr>;`,  `std::` is required by gcc (but not VS). I would like to get rid of those pesky namespaces as much as possible.

> Would you accept PRs to add std:: where it should be and #includes where they should be? 

I disagree with the word "should" here. It is really "where I want them to be". 
Your IDE not seeing headers is a separate problem. I am surprised such and advanced IDE doesn't understand such a simple use case. If there is really no way to make Qt Creator understand our includes then I guess we have no option but to add some includes. I just don't believe it, there must be some way to fix this in Qt Creator itself.

**Comment by cristianadam** [comment]
Currently Qt Creator only treats files as source files the files that it receives from CMake as source files. If you add a header file to the project, then CMake will report it to Qt Creator.

CMake does have all the information required from the underlying build system (ninja, make with dependencies), but this information is not available. See my feature request at https://gitlab.kitware.com/cmake/cmake/-/issues/24359

Since the user experience is suboptimal, I plan to add header detection in Qt Creator 14.
