### ISSUE TITLE
integrating litehtml with a UI framework

### ISSUE THREAD

**Issue by RalfSchallenberg** [litehtml/litehtml#8]
Hi, I'm trying to integrate litehtml with the UI framework JUCE. I don't just want to render some HTML, but I want to render UI dialogs with all their UI sub-elements like buttons etc using litehtml.
I need litehtml to tell me the sizes and positions of the sub-elements so I can position them correctly when the user resizes the dialog. Would this be possible somehow?
I'm not sure how I could map the dialog element hierarchy to litehtml/HTML/CSS.
Should every dialog element get its own HTML file to render its content or should I just render the whole dialog and all its elements with one HTML file and make the actual JUCE dialog elements transparent?
Any advice appreciated!

**Comment by tordex** [comment]
I have some ideas how to make UI using litehtml:
   * one dialog - one html file
   * use ```<input>``` tag or any custom tag for dialog elements
   * overwrite ```document_container::create_element``` to create your own implementation of dialog elements for ```<input>``` or custom tags. Make the array of the created elements on your side.

Now how to get the positions from litehtml. The positions become valid after you call ```document::render```, so just loop via your elements created via ```document_container::create_element```, call ```element::get_placement``` to get the element position and place them.

The implementation of the custom elements created via ```document_container::create_element``` depends of JUCE framework (I'm not familiar with it). Generally you have to implement ```element::render``` fill the ```element::m_pos``` data member with the valid position and size (relative to **x** and **y** parameters). Look the ```el_image::render``` as example. If you can make the actual JUCE dialog elements transparent - this can be useful because litehtml can draw elements (via your implementation). Also you can overwrite ```element::parse_styles``` and initialize JUCE dialog elements with proper styles.

Let me know if something unclear.
